[build]
  	publish = "dist/"
  	command = "make deploy"
	functions = "dist/server"

[build.environment]
  	NODE_OPTIONS = "--max_old_space_size=4096"

[[redirects]]
	from = "/reddit"
  	to = "https://reddit.com/u/marcysvoneylau"

[[redirects]]
  	from = "/twitter"
  	to = "https://twitter.com/yasiupl"

[[redirects]]
  	from = "/linkedin"
  	to = "https://www.linkedin.com/in/yasiupl"

[[redirects]]
  	from = "/github"
    to = "https://github.com/yasiupl"


[[redirects]]
  	from = "/patreon"
  	to = "https://www.patreon.com/yasiupl"

[[redirects]]
  	from = "/donate"
  	to = "https://www.patreon.com/yasiupl"

[[redirects]]
  	from = "/paypal"
  	to = "https://www.paypal.me/yasiupl"

[[redirects]]
  	from = "/youtube"
  	to = "https://www.youtube.com/channel/UCqFJAKOMWvS_oKHk9ppMC8w" 