[build]
  publish = "dist/"
  command = "make deploy"
  functions = "src/lambda"

[[redirects]]
	from = "/reddit"
  	to = "https://reddit.com/u/marcysvoneylau"

[[redirects]]
  	from = "/twitter"
  	to = "https://twitter.com/yasiupl"

[[redirects]]
  	from = "/linkedin"
  	to = "https://www.linkedin.com/in/yasiu"

[[redirects]]
  	from = "/github"
    	to = "https://github.com/yasiupl"

[[redirects]]
  	from = "/youtube"
  	to = "https://www.youtube.com/@yasiu" 
    
[[redirects]]
  	from = "/patreon"
  	to = "https://www.patreon.com/yasiupl"

[[redirects]]
  	from = "/paypal"
  	to = "https://www.paypal.me/yasiupl"

[[redirects]]
  	from = "/revolut"
  	to = "https://revolut.me/yasiu"

[[redirects]]
  	from = "/donate"
  	to = "/revolut"

[[redirects]]
  	from = "/keybase"
  	to = "https://keybase.io/yasiupl/"

[[redirects]]
  	from = "/ssh.pub"
  	to = "https://github.com/yasiupl.keys" 
	
[[redirects]]
  	from = "/pgp.pub"
  	to = "https://keybase.io/yasiupl/pgp_keys.asc?fingerprint=fe683591ae239dc2188c4bba1e3e8090e179f056"

[[redirects]]
  	from = "/web3"
  	to = "https://app.ens.domains/yasiu.pl"

[[redirects]]
  	from = "/avatar"
  	to = "https://euc.li/yasiu.pl"

[[redirects]]
  	from = "/header"
  	to = "https://euc.li/yasiu.pl/h"
	
